name: RunTests

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8]
        node: [ '10.x', '8.x' ]

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install pipenv
          pipenv install --dev --python ${{ matrix.python-version }}

      - name: Test with pytest
        run: |
          pipenv run pytest test/

      - name: Install npm packages
        run: |
          npm install

      - name: Run npm tests
        run: |
          npm test

#    - stage: test overlay files javascript
#      script:
#        # Pull the smallest possible docker image with node (npm) installed
#        - docker pull node:slim
#        - docker run -it -d --name app node:slim
#        - docker cp . app:/root/template
#        # Install dependencies because node_modules is in gitignore
#        - docker exec -i app bash -c "cd /root/template && npm install"
#        # Run tests
#        - docker exec -i app bash -c "cd /root/template && npm test"
#        - docker rm -f app